### ISSUE TITLE
Can't Install the node_modules

### ISSUE THREAD

**Issue by sebasalvarado** [devias-io/react-material-dashboard#7]
I am trying to run this application locally but I cannot get past the part of installing `node_modules`

My environment:
```
MacBook-Pro:react-material-dashboard sebastianalvarado$ node -v
v10.0.0
```
```
MacBook-Pro:react-material-dashboard sebastianalvarado$ npm -v
5.6.0
```

The error that I'm getting is the following:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.1.tgz: Request failed \"404 Not Found\"".
```

**Comment by devias-io** [comment]
Hi sebasalvarado,

Please remove `yarn.lock` and try again. This should fix your problem. For some reason the `.gitignore` file did not exclude this file from the commit. We will remove it in the next commit.

Thank you,
Devias Team

**Comment by sebasalvarado** [comment]
Thanks for your response, it did not fix it however. 

This is the output of a `yarn`:

```
MacBook-Pro:react-material-dashboard sebastianalvarado$ yarn
yarn install v1.10.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @material-ui/core > recompose > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning react-scripts > react-app-polyfill > core-js@2.6.4: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning react-scripts > fsevents@1.2.4: Way too old
warning react-scripts > workbox-webpack-plugin > workbox-build > joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning react-scripts > jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning react-scripts > postcss-preset-env > postcss-color-functional-notation > postcss-values-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning react-scripts > workbox-webpack-plugin > workbox-build > joi > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > workbox-webpack-plugin > workbox-build > joi > topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > workbox-webpack-plugin > workbox-build > joi > topo > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning react-scripts > jest > jest-cli > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
error Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/wast-parser@1.7.11" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/leb128@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:33701:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:111:13
    at run (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:95053:22)
    at /usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:95070:30
    at flush (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:94576:9)
    at process._tickCallback (internal/process/next_tick.js:172:11)
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/wast-printer@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:33701:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:111:13
    at run (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:95053:22)
    at /usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:95070:30
    at flush (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:94576:9)
    at process._tickCallback (internal/process/next_tick.js:172:11)
Error: Couldn't find package "@xtuc/ieee754@^1.2.0" required by "@webassemblyjs/ieee754@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:33701:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:111:13
    at run (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:95053:22)
    at /usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:95070:30
    at flush (/usr/local/Cellar/yarn/1.10.1/libexec/lib/cli.js:94576:9)
    at process._tickCallback (internal/process/next_tick.js:172:11)
```

Essentially the same error, can't find the package `"@xtuc/long@4.2.1" `. Looks like it's a WebAssembly dependancy. My yarn version is:
```
MacBook-Pro:react-material-dashboard sebastianalvarado$ yarn -v
1.10.1
```

Also, if I try `npm install` the error is more obscure. 
```
MacBook-Pro:react-material-dashboard sebastianalvarado$ npm install
npm WARN deprecated core-js@2.6.4: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastianalvarado/.npm/_logs/2019-05-13T15_12_12_515Z-debug.log
```

**Comment by devias-io** [comment]
Hi,

From the yarn log it seems that the error is generated by the IE11 polyfill, right? Could you please give me your repo url to see exactly why you're getting this error. Are you using Mac or Windows?

Also, in few minutes we are updating the project to a newer version using the latest material-ui package version.

**Comment by sebasalvarado** [comment]
This is my repo URL: https://github.com/sebasalvarado/react-material-dashboard 

I just cloned your latest version and the error seems to be the same. 

I am on a Mac OSX v10.14.3

**Comment by devias-io** [comment]
Hi again,

I cloned your project, used the same Node version (v10.0.0), but I was unable to replicate your problem. 

Later I ended up looking for people with the same [issue](https://github.com/yarnpkg/yarn/issues/6520) and is seems that you have to remove a file (if it exists) from `/Users/{your account}/.npmrc` (replace with your account). Also try to clean your npm cache using `npm cache clean --force`.

Let me know if it works.

**Comment by sebasalvarado** [comment]
Awesome! Thanks so much, I think that removing `.npmrc` file made it, for anyone having the problem in the future you need to remove this file if you still have it.
